Repository BME-MIT-IET/iet-hf-2022-lee-jangwoo, pull requests merged in 2022-05, with the labels that each got.

#9 Finished Exploratory testing
  .gitignore
  doc/Exploratory Testing Charter.md
  doc/exploratory_logs/bug_1000.PNG
  doc/exploratory_logs/bug_1000_exception.PNG
  doc/exploratory_logs/bug_1000_frozen.PNG
  doc/exploratory_logs/bug_1001.PNG
  doc/exploratory_logs/issue_500.PNG
  doc/exploratory_logs/issue_501_console.PNG
  doc/exploratory_logs/issue_501_ui.PNG
  doc/exploratory_logs/log.md
  doc/exploratory_logs/test_15_after.PNG
  doc/exploratory_logs/test_15_before.PNG
  src/main/java/Control.java
  testing_saves/test1.txt
  testing_saves/test2.txt
  testing_saves/test3.txt
  testing_saves/test4.txt
  testing_saves/test5.txt
  testing_saves/test6.txt
  testing_saves/test7.txt
  testing_saves/test8.txt
  testing_saves/test9.txt
Labels: test

#12 Exploratory testing bugs and issues resolved
  doc/doc.md
  src/main/java/controller/Control.java
  src/main/java/model/Asteroid.java
  src/main/java/view/GameFrame.java
  src/main/java/view/InventoryView.java
  testing_saves/test10.txt
Labels: bug, issue

#13 Fix bugs and code smells noted by SonarCloud and manual code review
  .gitignore
  de_facto_output_files/output_12.txt
  de_facto_output_files/output_13.txt
  de_facto_output_files/output_36.txt
  output_files/output_12.txt
  output_files/output_13.txt
  output_files/output_36.txt
  src/main/java/controller/BadGameFileFormatException.java
  src/main/java/controller/Control.java
  src/main/java/model/Asteroid.java
  src/main/java/model/Game.java
  src/main/java/model/INeighbour.java
  src/main/java/model/Ice.java
  src/main/java/model/Mineral.java
  src/main/java/model/Settler.java
  src/main/java/model/Sun.java
  src/main/java/model/Teleport.java
  src/main/java/model/Traveller.java
  src/main/java/model/UFO.java
  src/main/java/model/Uranium.java
  src/main/java/skeleton/Skeleton.java
  src/main/java/view/AsteroidView.java
  src/main/java/view/GameFrame.java
  src/main/java/view/InventoryView.java
  src/main/java/view/LevelView.java
  src/main/java/view/MineralButton.java
  src/main/java/view/RobotView.java
  src/main/java/view/SettlerView.java
  src/main/java/view/TeleportButton.java
  src/main/java/view/TeleportView.java
  src/main/java/view/TravellerView.java
  src/main/java/view/UFOView.java
  src/main/java/view/View.java
Labels: bug, sonar cloud
